# Generated by Django 5.0.8 on 2026-01-03 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('provider', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_sha256', models.CharField(max_length=64, unique=True)),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=512, null=True)),
                ('content_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('subject', models.CharField(blank=True, default='', max_length=998)),
                ('subject_norm', models.CharField(blank=True, default='', max_length=998)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('internal_date', models.DateTimeField(blank=True, null=True)),
                ('in_reply_to', models.CharField(blank=True, default='', max_length=512)),
                ('references_json', models.JSONField(blank=True, default=list)),
                ('body_text', models.TextField(blank=True, default='')),
                ('body_html', models.TextField(blank=True, default='')),
                ('size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_hash', models.CharField(max_length=128, unique=True)),
                ('primary_email', models.EmailField(max_length=254)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_key', models.CharField(max_length=128, unique=True)),
                ('subject_norm', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('delimiter', models.CharField(blank=True, default='/', max_length=8)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailboxes', to='imap2django.account')),
            ],
            options={
                'unique_together': {('account', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, default='', max_length=512)),
                ('content_type', models.CharField(blank=True, default='', max_length=255)),
                ('size', models.IntegerField(default=0)),
                ('part_id', models.CharField(blank=True, default='', max_length=64)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('storage_url', models.CharField(blank=True, default='', max_length=1024)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='imap2django.message')),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('to', 'TO'), ('cc', 'CC'), ('bcc', 'BCC')], max_length=8)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='imap2django.message')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='imap2django.person')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='imap2django.thread'),
        ),
        migrations.CreateModel(
            name='ImportCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailbox_name', models.CharField(max_length=255)),
                ('last_uid', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='imap2django.account')),
            ],
            options={
                'unique_together': {('account', 'mailbox_name')},
            },
        ),
        migrations.CreateModel(
            name='MailboxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.BigIntegerField()),
                ('flags_json', models.JSONField(blank=True, default=list)),
                ('modseq', models.BigIntegerField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailbox_messages', to='imap2django.mailbox')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailbox_messages', to='imap2django.message')),
            ],
            options={
                'unique_together': {('mailbox', 'uid')},
            },
        ),
    ]
